# Generated by Django 5.0.6 on 2025-11-18 15:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('calculus', 'حسابان'), ('geometry', 'هندسه'), ('discrete', 'گسسته'), ('chemistry', 'شیمی'), ('physics', 'فیزیک'), ('social_identity', 'هویت اجتماعی'), ('health', 'سلامت بهداشت'), ('persian', 'فارسی'), ('arabic', 'عربی'), ('english', 'زبان انگلیسی'), ('religion', 'دینی'), ('family_management', 'مدیریت خانواده')], max_length=50)),
                ('exam_date', models.DateField(default=django.utils.timezone.localdate)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نمره/ارزیابی',
                'verbose_name_plural': 'نمرات و ارزیابی\u200cها',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'چک\u200cلیست روزانه',
                'verbose_name_plural': 'چک\u200cلیست\u200cهای روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('importance', models.DecimalField(decimal_places=2, default=10, help_text='اهمیت از 1 تا 20؛ امکان اعشار دو رقم.', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الگوی کار روزانه',
                'verbose_name_plural': 'الگوهای کار روزانه',
                'ordering': ['-is_builtin', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('calculus', 'حسابان'), ('geometry', 'هندسه'), ('discrete', 'گسسته'), ('chemistry', 'شیمی'), ('physics', 'فیزیک'), ('social_identity', 'هویت اجتماعی'), ('health', 'سلامت بهداشت'), ('persian', 'فارسی'), ('arabic', 'عربی'), ('english', 'زبان انگلیسی'), ('religion', 'دینی'), ('family_management', 'مدیریت خانواده')], max_length=50, unique=True)),
                ('total_videos', models.PositiveIntegerField()),
                ('target_per_day', models.PositiveIntegerField(default=0, help_text='اختیاری: هدف روزانه برای مشاهده ویدیو')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'برنامه ویدیو',
                'verbose_name_plural': 'برنامه\u200cهای ویدیو',
            },
        ),
        migrations.CreateModel(
            name='VideoWatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('calculus', 'حسابان'), ('geometry', 'هندسه'), ('discrete', 'گسسته'), ('chemistry', 'شیمی'), ('physics', 'فیزیک'), ('social_identity', 'هویت اجتماعی'), ('health', 'سلامت بهداشت'), ('persian', 'فارسی'), ('arabic', 'عربی'), ('english', 'زبان انگلیسی'), ('religion', 'دینی'), ('family_management', 'مدیریت خانواده')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('videos_watched', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مشاهده ویدیو',
                'verbose_name_plural': 'گزارش\u200cهای مشاهده ویدیو',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='planner.dailychecklist')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='planner.dailytasktemplate')),
            ],
            options={
                'verbose_name': 'وضعیت کار روزانه',
                'verbose_name_plural': 'وضعیت\u200cهای کار روزانه',
                'unique_together': {('task_template', 'checklist')},
            },
        ),
    ]
