# Generated by Django 5.0.6 on 2025-11-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_seed_default_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رویداد تقویم',
                'verbose_name_plural': 'رویدادهای تقویم',
                'ordering': ['date', 'title'],
            },
        ),
    ]
